In [1]:
from keras.datasets import mnist
from keras import models
from keras import layers
from tensorflow.keras.utils import to_categorical

In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [5]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])

In [6]:
network.layers[0].get_weights()

[array([[ 0.02472739,  0.05877459,  0.00442425, ..., -0.02304155,
         -0.0533356 ,  0.0543242 ],
        [ 0.04066125,  0.00559235,  0.04849152, ..., -0.02356967,
          0.01653023, -0.06491715],
        [ 0.06221879, -0.02462877, -0.02720245, ..., -0.02281775,
          0.03278246,  0.05999176],
        ...,
        [-0.03061115,  0.06503946, -0.06454211, ..., -0.00459011,
          0.02705065, -0.05427466],
        [ 0.04100621,  0.06382249,  0.02381824, ..., -0.00537962,
         -0.04234625, -0.01179031],
        [-0.06804039,  0.06507641, -0.06287319, ..., -0.02888824,
          0.06311926, -0.01956854]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [4]:
network.layers[0].get_weights()

[array([[ 0.04531656, -0.0464482 ,  0.06705086, ...,  0.06247322,
          0.04586861, -0.04099269],
        [-0.04465284,  0.05948603,  0.00065952, ..., -0.05916428,
         -0.04340463,  0.06016785],
        [ 0.04933783,  0.00876564, -0.01561565, ...,  0.03095542,
          0.04086123, -0.06759714],
        ...,
        [-0.01465089,  0.00334558,  0.03737102, ..., -0.06611485,
          0.031903  ,  0.01231872],
        [ 0.02840438, -0.01522023, -0.05440728, ...,  0.03345452,
          0.0370845 ,  0.05732276],
        [ 0.05708613,  0.03783377,  0.02395023, ..., -0.05114667,
          0.05147482, -0.01861731]], dtype=float32),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [37]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [38]:
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

In [39]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 16s 32ms/step - loss: 0.2574 - accuracy: 0.9255
Epoch 2/5
469/469 [==============================] - 15s 32ms/step - loss: 0.1032 - accuracy: 0.9698
Epoch 3/5
469/469 [==============================] - 15s 33ms/step - loss: 0.0678 - accuracy: 0.9798
Epoch 4/5
469/469 [==============================] - 17s 36ms/step - loss: 0.0494 - accuracy: 0.9849
Epoch 5/5
469/469 [==============================] - 19s 41ms/step - loss: 0.0376 - accuracy: 0.9888


In [40]:
test_loss, test_acc = network.evaluate(test_images, test_labels)

313/313 [==============================] - 3s 8ms/step - loss: 0.0728 - accuracy: 0.9770


In [41]:
print('test_acc:', test_acc)

test_acc: 0.9769999980926514


In [52]:
network.layers[1].get_weights()

[array([[-0.00690989, -0.29885238, -0.01275255, ..., -0.25033593,
          0.0080703 ,  0.02926899],
        [ 0.22520259, -0.13039827, -0.09767022, ..., -0.29139215,
          0.08006287,  0.02649548],
        [-0.36918375,  0.20722054, -0.1471241 , ..., -0.17253026,
         -0.27695674,  0.11397595],
        ...,
        [ 0.00192534, -0.02752967,  0.02991549, ..., -0.02130324,
          0.05980236,  0.03403162],
        [-0.03385339, -0.02375948, -0.05521326, ..., -0.10278632,
          0.04885866, -0.02914503],
        [ 0.04113409,  0.11856584,  0.11906404, ..., -0.3535676 ,
         -0.25507113, -0.4153879 ]], dtype=float32),
 array([-0.05123803, -0.00207437,  0.00033051, -0.0290489 ,  0.00537397,
         0.03404855, -0.0336061 , -0.01193449,  0.05342064, -0.00116276],
       dtype=float32)]

In [51]:
network.layers[0].get_weights()

[array([[ 0.04164369,  0.04216243,  0.03884152, ..., -0.0354769 ,
          0.00709568, -0.03176429],
        [-0.04911757,  0.06546128, -0.04085933, ..., -0.01888759,
          0.0574093 , -0.0167224 ],
        [ 0.06481524, -0.05508289, -0.01443662, ..., -0.01336886,
          0.03150508,  0.04224259],
        ...,
        [-0.01263181,  0.01261317, -0.03909203, ..., -0.06279799,
          0.04386416, -0.04475879],
        [-0.03410641,  0.02797931,  0.03335558, ...,  0.01830343,
          0.01115202,  0.00511902],
        [-0.04074216,  0.06184196,  0.02772196, ...,  0.00449018,
          0.00824928,  0.04733521]], dtype=float32),
 array([-3.03432867e-02,  7.03647584e-02,  1.17708463e-02, -1.57364202e-03,
         1.38725406e-02, -3.62772215e-03, -4.00259718e-02,  1.29585089e-02,
        -2.17701383e-02,  3.01296497e-03,  1.13753797e-02, -3.98076512e-02,
        -4.96074632e-02, -6.29810710e-03,  8.30313265e-02, -1.01726875e-02,
         3.56394388e-02, -1.76958833e-03, -2.28174846e